from pathlib import Path
from typing import Any

import typer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

from vulnara.core.config_loader import ConfigLoader
from vulnara.core.exceptions import VulnaraError
from vulnara.core.logger import ConsoleLogger
from vulnara.core.orchestrator import ScanOrchestrator
from vulnara.models.finding import Finding

app = typer.Typer(
    name="vulnara",
    help="Vulnara Terminal Edition: authorized security assessment automation.",
    add_completion=False,
    no_args_is_help=False,
)

console = Console()
logger = ConsoleLogger()


def print_banner() -> None:
    """Render the Vulnara Terminal Edition banner."""

    banner = r"""
 _    __      __
| |  / /_  __/ /___  ____ ___________ _
| | / / / / / / __ \/ __ `/ ___/ __ `/
| |/ / /_/ / / / / / /_/ / /  / /_/ /
|___/\__,_/_/_/ /_/\__,_/_/   \__,_/
"""

    banner_text = Text(banner, style="bold cyan")
    subtitle = Text(
        "\nTerminal Edition v0.1.0\nAuthorized Security Assessment Automation",
        style="dim white",
    )

    console.print(
        Panel.fit(
            Text.assemble(banner_text, subtitle),
            border_style="cyan",
            padding=(1, 4),
        )
    )


def print_findings_table(findings: list[Finding]) -> None:
    """Render a compact terminal findings table."""

    if not findings:
        logger.success("No findings were generated by the current rule set.")
        return

    table = Table(title="Findings Summary", border_style="cyan")
    table.add_column("Severity", style="bold")
    table.add_column("Title")
    table.add_column("Category")

    for finding in findings:
        table.add_row(
            finding.severity.upper(),
            finding.title,
            finding.category,
        )

    console.print(table)



def print_passive_recon_summary(passive_results: dict[str, Any]) -> None:
    robots = passive_results.get("robots")

    if isinstance(robots, dict):
        if robots.get("skipped"):
            logger.info(str(robots.get("reason", "robots module skipped.")))
        elif robots.get("error"):
            logger.warning(f"robots.txt check failed: {robots.get('error')}")
        elif robots.get("found"):
            entries = robots.get("entries", {})
            disallow_count = len(entries.get("disallow", [])) if isinstance(entries, dict) else 0
            sitemap_count = len(entries.get("sitemap", [])) if isinstance(entries, dict) else 0

            logger.success(f"robots.txt found: {robots.get('url', '')}")
            logger.info(f"robots.txt disallow rules: {disallow_count}")
            logger.info(f"robots.txt sitemap references: {sitemap_count}")
        else:
            logger.info(f"robots.txt not found. Status: {robots.get('status_code', '')}")

    sitemap = passive_results.get("sitemap")

    if isinstance(sitemap, dict):
        if sitemap.get("skipped"):
            logger.info(str(sitemap.get("reason", "sitemap module skipped.")))
        elif sitemap.get("error"):
            logger.warning(f"sitemap.xml check failed: {sitemap.get('error')}")
        elif sitemap.get("found"):
            logger.success(f"sitemap.xml found: {sitemap.get('url', '')}")
            logger.info(f"sitemap.xml URLs collected: {sitemap.get('url_count', 0)}")
        else:
            logger.info(f"sitemap.xml not found. Status: {sitemap.get('status_code', '')}")

@app.callback(invoke_without_command=True)
def main(ctx: typer.Context) -> None:
    """Vulnara Terminal Edition command entry point."""

    if ctx.invoked_subcommand is None:
        print_banner()
        console.print(
            "[dim]Use [bold cyan]python main.py --help[/bold cyan] to see available commands.[/dim]\n"
        )


@app.command()
def doctor() -> None:
    """Validate the local Vulnara project setup."""

    project_root = Path.cwd()
    config_loader = ConfigLoader(project_root=project_root)

    try:
        settings = config_loader.load_settings()
        profiles = config_loader.load_scan_profiles()
    except VulnaraError as error:
        logger.error(str(error))
        raise typer.Exit(code=1) from error

    app_info: dict[str, Any] = settings.get("app", {})
    profile_names = sorted((profiles.get("profiles") or {}).keys())

    print_banner()
    logger.success("Project setup looks valid.")
    logger.info(f"Application: {app_info.get('name', 'Vulnara')}")
    logger.info(f"Edition: {app_info.get('edition', 'Terminal Edition')}")
    logger.info(f"Version: {app_info.get('version', 'unknown')}")
    logger.info(f"Available profiles: {', '.join(profile_names)}")


@app.command()
def scan(
    target: str = typer.Argument(
        ...,
        help="Target URL, for example https://example.com",
    ),
    authorized_domain: str = typer.Option(
        ...,
        "--authorized-domain",
        "-d",
        help="Authorized domain used for scope validation.",
    ),
    profile: str = typer.Option(
        "passive_recon",
        "--profile",
        "-p",
        help="Scan profile to use.",
    ),
    ai_report: bool = typer.Option(
        False,
        "--ai",
        help="Generate an optional AI-assisted report summary.",
    ),
) -> None:
    """Run a safe assessment workflow against an authorized target."""

    print_banner()

    logger.info(f"Target: [bold white]{target}[/bold white]")
    logger.info(f"Authorized domain: [bold white]{authorized_domain}[/bold white]")
    logger.info(f"Profile: [bold white]{profile}[/bold white]")

    if ai_report:
        logger.info("AI analysis: [bold green]enabled[/bold green]")
    else:
        logger.info("AI analysis: [bold yellow]disabled[/bold yellow]")

    project_root = Path.cwd()
    config_loader = ConfigLoader(project_root=project_root)

    try:
        settings = config_loader.load_settings()
        scan_profiles = config_loader.load_scan_profiles()

        logger.info("Running orchestrated assessment workflow.")
        result = ScanOrchestrator(
            project_root=project_root,
            settings=settings,
            scan_profiles=scan_profiles,
        ).run(
            target_url=target,
            authorized_domain=authorized_domain,
            profile_name=profile,
        )
    except VulnaraError as error:
        logger.error(str(error))
        raise typer.Exit(code=1) from error

    logger.success("Scan workflow completed.")
    logger.success("Scope validation passed.")
    logger.info(f"Validated hostname: [bold white]{result.target.hostname}[/bold white]")
    logger.info(f"Base URL: [bold white]{result.target.base_url}[/bold white]")

    logger.success("HTTP probe completed.")
    logger.info(f"Final URL: [bold white]{result.http_result.get('url', '')}[/bold white]")
    logger.info(
        f"Status: [bold white]{result.http_result.get('status_code', '')} "
        f"{result.http_result.get('reason_phrase', '')}[/bold white]"
    )

    page_title = str(result.http_result.get("title", "")).strip()
    if page_title:
        logger.info(f"Page title: [bold white]{page_title}[/bold white]")

    if result.header_result.get("skipped"):
        logger.info(str(result.header_result.get("reason", "Security header analysis skipped.")))
    else:
        missing_headers = result.header_result.get("missing_headers", [])
        if isinstance(missing_headers, list) and missing_headers:
            logger.warning(f"Missing security headers: {', '.join(missing_headers)}")
        else:
            logger.success("No missing security headers detected by the current rule set.")

        server_header = str(result.header_result.get("server_header", "")).strip()
        if server_header:
            logger.info(f"Server header: [bold white]{server_header}[/bold white]")

    print_passive_recon_summary(result.passive_results)

    logger.success(f"Findings generated: {result.finding_count}")
    print_findings_table(result.findings)

    logger.success(f"Evidence saved: {result.evidence_path}")
    logger.success(f"Report saved: {result.report_path}")


@app.command()
def version() -> None:
    """Show the current Vulnara version."""

    logger.info("Vulnara Terminal Edition 0.1.0")

