from pathlib import Path
from typing import Any

import typer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

from vulnara.core.config_loader import ConfigLoader
from vulnara.core.exceptions import ScopeValidationError, VulnaraError
from vulnara.core.logger import ConsoleLogger
from vulnara.core.scope import ScopeValidator
from vulnara.findings.rules import FindingRuleEngine
from vulnara.models.finding import Finding
from vulnara.modules.recon.headers import HeaderScanner
from vulnara.modules.recon.http_probe import HttpProbe

app = typer.Typer(
    name="vulnara",
    help="Vulnara Terminal Edition: authorized security assessment automation.",
    add_completion=False,
    no_args_is_help=False,
)

console = Console()
logger = ConsoleLogger()


def print_banner() -> None:
    """Render the Vulnara Terminal Edition banner."""

    banner = r"""
 _    __      __
| |  / /_  __/ /___  ____ ___________ _
| | / / / / / / __ \/ __ `/ ___/ __ `/
| |/ / /_/ / / / / / /_/ / /  / /_/ /
|___/\__,_/_/_/ /_/\__,_/_/   \__,_/
"""

    banner_text = Text(banner, style="bold cyan")
    subtitle = Text(
        "\nTerminal Edition v0.1.0\nAuthorized Security Assessment Automation",
        style="dim white",
    )

    console.print(
        Panel.fit(
            Text.assemble(banner_text, subtitle),
            border_style="cyan",
            padding=(1, 4),
        )
    )


def print_findings_table(findings: list[Finding]) -> None:
    """Render a compact terminal findings table."""

    if not findings:
        logger.success("No findings were generated by the current rule set.")
        return

    table = Table(title="Findings Summary", border_style="cyan")
    table.add_column("Severity", style="bold")
    table.add_column("Title")
    table.add_column("Category")

    for finding in findings:
        table.add_row(
            finding.severity.upper(),
            finding.title,
            finding.category,
        )

    console.print(table)


@app.callback(invoke_without_command=True)
def main(ctx: typer.Context) -> None:
    """Vulnara Terminal Edition command entry point."""

    if ctx.invoked_subcommand is None:
        print_banner()
        console.print(
            "[dim]Use [bold cyan]python main.py --help[/bold cyan] to see available commands.[/dim]\n"
        )


@app.command()
def doctor() -> None:
    """Validate the local Vulnara project setup."""

    project_root = Path.cwd()
    config_loader = ConfigLoader(project_root=project_root)

    try:
        settings = config_loader.load_settings()
        profiles = config_loader.load_scan_profiles()
    except VulnaraError as error:
        logger.error(str(error))
        raise typer.Exit(code=1) from error

    app_info: dict[str, Any] = settings.get("app", {})
    profile_names = sorted((profiles.get("profiles") or {}).keys())

    print_banner()
    logger.success("Project setup looks valid.")
    logger.info(f"Application: {app_info.get('name', 'Vulnara')}")
    logger.info(f"Edition: {app_info.get('edition', 'Terminal Edition')}")
    logger.info(f"Version: {app_info.get('version', 'unknown')}")
    logger.info(f"Available profiles: {', '.join(profile_names)}")


@app.command()
def scan(
    target: str = typer.Argument(
        ...,
        help="Target URL, for example https://example.com",
    ),
    authorized_domain: str = typer.Option(
        ...,
        "--authorized-domain",
        "-d",
        help="Authorized domain used for scope validation.",
    ),
    profile: str = typer.Option(
        "passive_recon",
        "--profile",
        "-p",
        help="Scan profile to use.",
    ),
    ai_report: bool = typer.Option(
        False,
        "--ai",
        help="Generate an optional AI-assisted report summary.",
    ),
) -> None:
    """Run a safe assessment workflow against an authorized target."""

    print_banner()

    logger.info(f"Target: [bold white]{target}[/bold white]")
    logger.info(f"Authorized domain: [bold white]{authorized_domain}[/bold white]")
    logger.info(f"Profile: [bold white]{profile}[/bold white]")

    if ai_report:
        logger.info("AI analysis: [bold green]enabled[/bold green]")
    else:
        logger.info("AI analysis: [bold yellow]disabled[/bold yellow]")

    try:
        target_info = ScopeValidator().validate_target(
            target_url=target,
            authorized_domain=authorized_domain,
        )
    except ScopeValidationError as error:
        logger.error(str(error))
        raise typer.Exit(code=1) from error

    logger.success("Scope validation passed.")
    logger.info(f"Validated hostname: [bold white]{target_info.hostname}[/bold white]")
    logger.info(f"Base URL: [bold white]{target_info.base_url}[/bold white]")

    project_root = Path.cwd()
    config_loader = ConfigLoader(project_root=project_root)

    try:
        settings = config_loader.load_settings()
    except VulnaraError as error:
        logger.error(str(error))
        raise typer.Exit(code=1) from error

    network_settings: dict[str, Any] = settings.get("network", {})
    timeout_seconds = int(network_settings.get("timeout_seconds", 10))
    follow_redirects = bool(network_settings.get("follow_redirects", True))
    user_agent = str(network_settings.get("user_agent", "Vulnara/0.1"))

    logger.info("Running HTTP probe.")
    http_result = HttpProbe(
        timeout_seconds=timeout_seconds,
        follow_redirects=follow_redirects,
        user_agent=user_agent,
    ).run(target_info)

    if not http_result.get("success"):
        logger.error(f"HTTP probe failed: {http_result.get('error', 'unknown error')}")
        raise typer.Exit(code=1)

    logger.success("HTTP probe completed.")
    logger.info(f"Final URL: [bold white]{http_result.get('url', '')}[/bold white]")
    logger.info(
        f"Status: [bold white]{http_result.get('status_code', '')} "
        f"{http_result.get('reason_phrase', '')}[/bold white]"
    )

    page_title = str(http_result.get("title", "")).strip()
    if page_title:
        logger.info(f"Page title: [bold white]{page_title}[/bold white]")

    logger.info("Running security header analysis.")
    header_result = HeaderScanner().run(http_result)

    missing_headers = header_result.get("missing_headers", [])
    if isinstance(missing_headers, list) and missing_headers:
        logger.warning(f"Missing security headers: {', '.join(missing_headers)}")
    else:
        logger.success("No missing security headers detected by the current rule set.")

    server_header = str(header_result.get("server_header", "")).strip()
    if server_header:
        logger.info(f"Server header: [bold white]{server_header}[/bold white]")

    raw_results = {
        "http_probe": http_result,
        "headers": header_result,
    }

    logger.info("Generating findings.")
    findings = FindingRuleEngine().build_findings(
        target=target_info,
        raw_results=raw_results,
    )

    logger.success(f"Findings generated: {len(findings)}")
    print_findings_table(findings)

    logger.success("Findings engine completed. Evidence storage will be connected in Milestone 5.")


@app.command()
def version() -> None:
    """Show the current Vulnara version."""

    logger.info("Vulnara Terminal Edition 0.1.0")