from dataclasses import asdict, dataclass


@dataclass(frozen=True)
class Finding:
    """Represents a normalized security finding generated by Vulnara."""

    title: str
    severity: str
    description: str
    recommendation: str
    evidence: str
    category: str = "configuration"

    def to_dict(self) -> dict[str, str]:
        return asdict(self)